### ISSUE TITLE
Testcafe teamcity reporter is not working with version 1.16

### ISSUE THREAD

**Issue by kkraft7** [Soluto/testcafe-reporter-teamcity#10]
I am no longer getting teamcity-formatted output when I use the teamcity reporter option after upgrading to TestCafe version 1.16. I works correctly when I use TestCafe version 1.14.2. Note that I am also seeing this issue with TestCafe version 15.

I have tried the following options:

1. --reporter teamcity
2. --reporters teamcity
3. -r teamcity

**Comment by DRiewaldt** [comment]
I just installed this and it's also not working for me. I don't see a file or output anywhere.

I ran with --reporter teamcity. I see it in my packages, and got no errors from using it. Just no output or results of any kind are displayed.

**Comment by ebickle** [comment]
Thanks for your request! This project hasn't been maintained in a few years now, so I'll be marking it as deprecated and archiving it.
