### ISSUE TITLE
Add support for additional test metadata 

### ISSUE THREAD

**Issue by fkrauthan** [Soluto/testcafe-reporter-teamcity#4]
Since teamcity 2018.2 the added support to report additional test metedata (e.g. screenshots). See this [guide](https://confluence.jetbrains.com/display/TCD18/Reporting+Test+Metadata) for more details.

It would be nice that it could automatic link the following information:

- Test Failure Screenshot (if enabled)
- Test emitted Screenshots (manual created screenshots)
- Test Videos (if enabled)

**Comment by ebickle** [comment]
Thanks for your request! This project hasn't been maintained in a few years now, so I'll be marking it as deprecated and archiving it.
