### ISSUE TITLE
Report browser name as part of test name

### ISSUE THREAD

**Issue by fkrauthan** [Soluto/testcafe-reporter-teamcity#5]
It would be great if the reporter could report the browser name as part of its test output (in case I run the testcafe multiple times for different browsers within one teamcity test project).

Currently it shows the same tests have run multiple times (once per browser).

**Comment by ebickle** [comment]
Thanks for your request! This project hasn't been maintained in a few years now, so I'll be marking it as deprecated and archiving it.
